services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    restart: always
    container_name: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - ecommerce-network

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    container_name: pgadmin
    ports:
      - 8081:80
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    depends_on:
      - db
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    networks:
      - ecommerce-network

  nestjs:
    build: .
    container_name: nestjs
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge